services:
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres-fastapi
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BROKER}
    ports:
      - "7000:7000"
    networks:
      - kafka-net

  postgres-fastapi:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-p", "5433"]
    ports:
      - "5433:5433"
    volumes:
      - mydbdata:/var/lib/postgresql/data
    networks:
      - kafka-net

volumes:
  mydbdata:

networks:
  kafka-net:
    external: true