services:
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - custom_postgres
      - redis
    ports:
      - "7000:7000"

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  custom_postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - mydbdata:/var/lib/postgresql/data

volumes:
  mydbdata:
  redis_data:
