services:
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres-fastapi:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BROKER}
    ports:
      - "7000:7000"
    networks:
      - kafka-net

  postgres-fastapi:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      retries: 5
    volumes:
      - mydbdata:/var/lib/postgresql/data
    networks:
      - kafka-net

volumes:
  mydbdata:

networks:
  kafka-net:
    external: true